on:
  push:
    branch:
      - "main"
      - "dev"

jobs:
  build:
    # Run a job for each of the specified target architectures:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout the sauce
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: MSVC setup
        uses: ilammy/msvc-dev-cmd@v1
      - name: MSVC compilation
        run: |
          cl /EHsc /std:c++17 /O2 forge.cpp /DEBUG:FULL
          ./forge.exe help

      - name: "Upload binary"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "forge"
          files: |
            forge.exe
            LICENSE.txt
            README.md
